--
-- PostgreSQL database dump
--

\restrict redI0TYDaA5gOjylSdyXlhDkOzKx9EJRRrIcd2GPabJq4gbUNUepIxaW1GD2aK5

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-27 16:44:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 17024)
-- Name: HistorialEstados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HistorialEstados" (
    "Id" integer NOT NULL,
    "ReporteId" integer NOT NULL,
    "EstadoAnterior" integer NOT NULL,
    "EstadoNuevo" integer NOT NULL,
    "FechaCambio" timestamp with time zone NOT NULL
);


ALTER TABLE public."HistorialEstados" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17023)
-- Name: HistorialEstados_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."HistorialEstados" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HistorialEstados_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 17003)
-- Name: Reportes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reportes" (
    "Id" integer NOT NULL,
    "Ubicacion" text NOT NULL,
    "Problema" text NOT NULL,
    "Descripcion" text,
    "Prioridad" integer NOT NULL,
    "Estado" integer NOT NULL,
    "ReportadoPorId" integer NOT NULL,
    "FechaReporte" timestamp with time zone NOT NULL,
    "FechaActualizacion" timestamp with time zone NOT NULL
);


ALTER TABLE public."Reportes" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17002)
-- Name: Reportes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reportes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reportes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16992)
-- Name: Usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Usuarios" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Correo" text NOT NULL
);


ALTER TABLE public."Usuarios" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16991)
-- Name: Usuarios_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Usuarios" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Usuarios_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16984)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5036 (class 0 OID 17024)
-- Dependencies: 225
-- Data for Name: HistorialEstados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."HistorialEstados" ("Id", "ReporteId", "EstadoAnterior", "EstadoNuevo", "FechaCambio") FROM stdin;
\.


--
-- TOC entry 5034 (class 0 OID 17003)
-- Dependencies: 223
-- Data for Name: Reportes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Reportes" ("Id", "Ubicacion", "Problema", "Descripcion", "Prioridad", "Estado", "ReportadoPorId", "FechaReporte", "FechaActualizacion") FROM stdin;
\.


--
-- TOC entry 5032 (class 0 OID 16992)
-- Dependencies: 221
-- Data for Name: Usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Usuarios" ("Id", "Nombre", "Correo") FROM stdin;
\.


--
-- TOC entry 5030 (class 0 OID 16984)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260927140638_InitialCreate	10.0.12
\.


--
-- TOC entry 5042 (class 0 OID 0)
-- Dependencies: 224
-- Name: HistorialEstados_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."HistorialEstados_Id_seq"', 1, false);


--
-- TOC entry 5043 (class 0 OID 0)
-- Dependencies: 222
-- Name: Reportes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Reportes_Id_seq"', 1, false);


--
-- TOC entry 5044 (class 0 OID 0)
-- Dependencies: 220
-- Name: Usuarios_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Usuarios_Id_seq"', 1, false);


--
-- TOC entry 4880 (class 2606 OID 17033)
-- Name: HistorialEstados PK_HistorialEstados; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HistorialEstados"
    ADD CONSTRAINT "PK_HistorialEstados" PRIMARY KEY ("Id");


--
-- TOC entry 4877 (class 2606 OID 17017)
-- Name: Reportes PK_Reportes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reportes"
    ADD CONSTRAINT "PK_Reportes" PRIMARY KEY ("Id");


--
-- TOC entry 4874 (class 2606 OID 17001)
-- Name: Usuarios PK_Usuarios; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuarios"
    ADD CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id");


--
-- TOC entry 4871 (class 2606 OID 16990)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4878 (class 1259 OID 17039)
-- Name: IX_HistorialEstados_ReporteId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_HistorialEstados_ReporteId" ON public."HistorialEstados" USING btree ("ReporteId");


--
-- TOC entry 4875 (class 1259 OID 17040)
-- Name: IX_Reportes_ReportadoPorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reportes_ReportadoPorId" ON public."Reportes" USING btree ("ReportadoPorId");


--
-- TOC entry 4872 (class 1259 OID 17041)
-- Name: IX_Usuarios_Correo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Usuarios_Correo" ON public."Usuarios" USING btree ("Correo");


--
-- TOC entry 4882 (class 2606 OID 17034)
-- Name: HistorialEstados FK_HistorialEstados_Reportes_ReporteId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HistorialEstados"
    ADD CONSTRAINT "FK_HistorialEstados_Reportes_ReporteId" FOREIGN KEY ("ReporteId") REFERENCES public."Reportes"("Id") ON DELETE CASCADE;


--
-- TOC entry 4881 (class 2606 OID 17018)
-- Name: Reportes FK_Reportes_Usuarios_ReportadoPorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reportes"
    ADD CONSTRAINT "FK_Reportes_Usuarios_ReportadoPorId" FOREIGN KEY ("ReportadoPorId") REFERENCES public."Usuarios"("Id") ON DELETE RESTRICT;


-- Completed on 2026-09-27 16:44:08

--
-- PostgreSQL database dump complete
--

\unrestrict redI0TYDaA5gOjylSdyXlhDkOzKx9EJRRrIcd2GPabJq4gbUNUepIxaW1GD2aK5

